[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_movies = "G4qKer2mVrNTSEBKEvMMdhjZ2JmdNYyonDkpHeWiiJGX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/diegocaminor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
